### ISSUE TITLE
Quantitative Comparison of NVS on the real dataset of DeblurNeRF

### ISSUE THREAD

**Issue by haeyun-choi** [taekkii/ExBluRF#3]
Thank you for the great work.

I'm leaving an issue because I want to ask a question about the quantitative comparison in the supplementary material.

I reproduced your work using the configuration files in the repository (e.g. blurball.txt, ...)
and also changed the order of the bezier curve from 9 to 7 following the paper.

However, the PSNR score was relatively lower than the table you recorded. (about 1.5 ~ 2dB)

Should I have changed other settings to reproduce your results?

Thank you again.

**Comment by taekkii** [comment]
Hi,
Did you use our bash script (eval.sh) to reproduce the result?

**Comment by haeyun-choi** [comment]
Thank you for your reply.

Yes, I did.

**Comment by taekkii** [comment]
Sorry for the delayed response.
Could you pick one of the scene and share the result of test view where the performance is not corresponding to the our table?
I think it is an alignment issue (i.e. export_colmap() in inference.py is not working as we expected).

**Comment by haeyun-choi** [comment]
This is one of the real-world scenes, named 'Decoration'.

This is the test_metrics.txt.

iter20000/globalstep20000: MSE:0.03832082 PSNR:20.22102752 SSIM:0.50536897 LPIPS:0.51310301 Time:0h 23m 42s Max_Memory:3780MiB
iter40000/globalstep40000: MSE:0.03675492 PSNR:20.39812465 SSIM:0.51334847 LPIPS:0.50587672 Time:0h 47m 30s Max_Memory:4278MiB
iter60000/globalstep60000: MSE:0.03509545 PSNR:20.61021190 SSIM:0.55482233 LPIPS:0.42763928 Time:1h 13m 3s Max_Memory:5970MiB
iter80000/globalstep80000: MSE:0.03514048 PSNR:20.60480373 SSIM:0.55593423 LPIPS:0.42097014 Time:1h 38m 34s Max_Memory:5970MiB
iter100000/globalstep100000: MSE:0.03453265 PSNR:20.69128404 SSIM:0.57863544 LPIPS:0.36440104 Time:2h 6m 49s Max_Memory:5970MiB
iter120000/globalstep120000: MSE:0.03433268 PSNR:20.71615738 SSIM:0.58103296 LPIPS:0.35763523 Time:2h 35m 12s Max_Memory:5970MiB
iter140000/globalstep140000: MSE:0.03451798 PSNR:20.69278452 SSIM:0.58609701 LPIPS:0.30955538 Time:3h 25m 40s Max_Memory:8982MiB
iter160000/globalstep160000: MSE:0.03458935 PSNR:20.68324729 SSIM:0.58628677 LPIPS:0.30198836 Time:4h 15m 52s Max_Memory:8982MiB
iter180000/globalstep180000: MSE:0.03461665 PSNR:20.67966904 SSIM:0.58641343 LPIPS:0.29921404 Time:5h 6m 13s Max_Memory:8982MiB
iter200000/globalstep200000: MSE:0.03462343 PSNR:20.67874494 SSIM:0.58647622 LPIPS:0.29804435 Time:5h 56m 41s Max_Memory:8982MiB

This is the test view 000.png.

![000](https://github.com/taekkii/ExBluRF/assets/94540583/1532d20b-352f-4df5-92a7-e81a9b10d207)


And this is the ground truth image 000.png

![00400](https://github.com/taekkii/ExBluRF/assets/94540583/40b25c8d-8e4c-4d2f-b228-debe67db9e7f)

**Comment by haeyun-choi** [comment]
Compared with the ground truth images, there are indeed alignment issues as you suspected. 

Are there any ways to prevent this?

**Comment by taekkii** [comment]
The test_metrics.txt is kinda redundant as it shows misaligned metrics only. We should've removed it from the main script. Sorry for causing a confusion.

To address the alignment issue between test and G.T images, we had re-registered the test image using COLMAP. Specifically, it means that we had:
1) acquired **training view pose** and **sharp rendering from the training view** . The training view pose is assumed to be center of the Bezier curve representing the estimated camera trajectory. Those (sharp image)-(sharp pose) pairs are fixed for evaluation.
2) Run triangulation using the pairs. (meaning acquisition of SfM point clouds from fixed poses) 
3) Registered test views to these point clouds. Then we now have a aligned poses for test views.

All of these processes are what "eval_$dataset.sh" should do.

---
Actually above strategy is not always solving the misalignment issue as you have pointed out. The majority of works these days (tackling 3D reconstruction from pose-unknown or motion blur tasks) , where we "optimize" initial camera poses and such misalignment issue happens, prefer to perform test-time pose optimization like iNeRF style (see test.py from [DeblurGS](https://github.com/taekkii/deblurgs), for example).  I suggest you to implement such test-time pose optimization if you really want to measure true PSNR without alignment issue.

Thank you.

**Comment by haeyun-choi** [comment]
I appreciate the detailed response. Thanks to your explanation, I now understand the cause of the problem and the solutions. Once again, I appreciate your excellent work and will close the issue.

**Comment by GopiRajuMatta** [comment]
Hello @taekkii, @Hae-koos!

If you had figured out the code for the same, can you please share.


Thank you
Gopi
